Revert "Replace Sentinel with ChunkLock"
This patch fails to build on a number of GCC 4.9 architectures:

    phosphor/include/phosphor/chunk_lock.h>:206:15: error:
    'is_trivially_constructible' is not a member of 'std'

This reverts commit 9eb4d31ebf1501e97aa8a3b353b628934d81e14c.

Change-Id: Ied9ebdbdb341d33eb3e02ed92b14a7246b2a4f29
Reviewed-on: http://review.couchbase.org/80553
Reviewed-by: Dave Rigby <daver@couchbase.com>
Tested-by: Dave Rigby <daver@couchbase.com>